### ISSUE TITLE
Plugin returns error at server launch

### ISSUE THREAD

**Issue by kaione** [smartiniOnGitHub/grails-angularjs-resources#19]
Here is the error poping in the console when I launch the server:

[localhost-startStop-1] ERROR resource.ResourceProcessor  - Unable to load resources
java.lang.NullPointerException: Cannot get property 'pluginDir' on null object
    at AngularjsResources.getResources(AngularjsResources.groovy:23)
    at AngularjsResources$_run_closure1_closure4.doCall(AngularjsResources.groovy:11)
    at org.grails.plugin.resource.module.ModulesBuilder.invokeMethod(ModulesBuilder.groovy:46)
    at AngularjsResources$_run_closure1.doCall(AngularjsResources.groovy:8)
    at org.grails.plugin.resource.ResourceProcessor$_loadModules_closure18.doCall(ResourceProcessor.groovy:848)
    at org.grails.plugin.resource.ResourceProcessor.loadModules(ResourceProcessor.groovy:842)
    at org.grails.plugin.resource.ResourceProcessor.reloadAll(ResourceProcessor.groovy:1135)
    at ResourcesGrailsPlugin$_closure3.doCall(ResourcesGrailsPlugin.groovy:166)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Comment by smartiniOnGitHub** [comment]
Hi,
can you give me more details on your environment (OS, JDK, Grails version) ?
Did you tried with a new test webapp depending only on this plugin and latest Resources 1.2.14 (and jQuery) and no other dependencies ?
Last, If you try with one of my test webapps (one for Grails-2.2.5 and another for Grails-2.4.4) do you get the same error ?

Tell me.
Bye

**Comment by smartiniOnGitHub** [comment]
Closing until more info are given.
